name: context_plus_lint
description: Custom lint rules for context_plus
version: 1.0.0-rc.1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
