name: context_ref
description: A hassle-free way to provide and retrieve values for a BuildContext
version: 3.2.1
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_ref
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_ref
topics:
  - reactive
  - ui
  - state-management
  - extension

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  context_plus_core: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  context_watch: ^7.0.0

flutter:
