name: context_plus_utils
description: "A collection of utilities based on context_plus, tailored for various use cases"
version: 1.0.2
homepage: https://github.com/s0nerik/context_plus/tree/main/packages/context_plus_utils
repository: https://github.com/s0nerik/context_plus/tree/main/packages/context_plus_utils

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  context_plus: ^6.0.3
  context_plus_core: ^1.0.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: